Repository hmcts/civil-general-applications, pull requests merged in 2023-08, with the labels that each got.

#1097 CIV-5339 - Release 2 - LIP v LIP Update Access Profile
  bin/add-roles.sh
  config/owasp/suppressions.xml
Labels: prd:civil, ns:civil, rel:civil-general-applications-pr-1097

#1104 CIV-00000 Modified naming pattern for branches
  .github/workflows/main.yml
Labels: prd:civil, ns:civil, rel:civil-general-applications-pr-1104

#1096 CIV-9618 removed duplicate event trigger
  src/main/java/uk/gov/hmcts/reform/civil/service/PaymentRequestUpdateCallbackService.java
  src/main/java/uk/gov/hmcts/reform/civil/service/StateGeneratorService.java
  src/test/java/uk/gov/hmcts/reform/civil/service/PaymentRequestUpdateCallbackServiceTest.java
  src/test/java/uk/gov/hmcts/reform/civil/service/StateGeneratorServiceTest.java
Labels: prd:civil, ns:civil, rel:civil-general-applications-pr-1096
